---
project_name: Sample Project
url: https://www.zara.com/us/en/ribbed-leggings-with-pockets-p06201561.html?v1=21677898&v2=1283656
target:
  name: div
  class: size-list

sender:
  user: someuser@gmail.com
  pwd: password
recipient:
  - someuser@gmail.com

sleep:
  min: 120
  max: 500
...